language: node_js

node_js :
  - node

install:
  - npm install

script:
  - npm run lint
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: main